global-client-fingerprint: chrome
dns:
  enable: true
  ipv6: true
  enhanced-mode: fake-ip
  nameserver:
  - https://dns.alidns.com/dns-query
  - https://doh.pub/dns-query
  - https://doh.360.cn/dns-query
  - https://doh.opendns.com/dns-query
  fallback:
  - https://8.8.8.8/dns-query
  - https://8.8.4.4/dns-query
  - https://1.1.1.1/dns-query
  - https://1.0.0.1/dns-query
  fallback-filter:
    geoip: true
    geoip-code: CN
    geosite:
      - gfw
    ipcidr:
      - 240.0.0.0/4
    domain:
      - '+.google.com'
      - '+.facebook.com'
      - '+.youtube.com'
