global-client-fingerprint: chrome
dns:
  enable: true
  ipv6: true
  enhanced-mode: fake-ip
  fake-ip-filter:
    - '*.lan'
    - '*.cn'
    - '*.qq.com'
  default-nameserver:
    - 1.1.1.1
    - 8.8.8.8
    - 223.5.5.5
    - 114.114.114.114
  nameserver:
    - https://doh.pub/dns-query
    - https://dns.alidns.com/dns-query
    - https://doh.360.cn/dns-query
    - 114.114.114.114
    - 223.5.5.5
  fallback:
    - https://dns.aiwanyun.cn/dns-query
    - https://cloudflare-dns.com/dns-query
    - https://dns.google/dns-query
  fallback-filter:
    geoip: true
    geoip-code: CN
    geosite:
      - gfw
    ipcidr:
      - 240.0.0.0/4
    domain:
      - '+.google.com'
      - '+.facebook.com'
      - '+.youtube.com'
