[custom]

;设置规则标志位
ruleset=🎯 全球直连,https://raw.githubusercontent.com/ZY-Zeng/ZJU_Rule/refs/heads/master/Clash/Ruleset/PrivateTracker.list
ruleset=✔ ZJU内网,https://raw.githubusercontent.com/ZY-Zeng/ZJU_Rule/refs/heads/master/Clash/ZJU-Rule.list
ruleset=✔ ZJU内网,https://raw.githubusercontent.com/ZY-Zeng/ZJU_Rule/refs/heads/master/Clash/ZJU.list
ruleset=📃 ZJU More Scholar,https://raw.githubusercontent.com/ZY-Zeng/ZJU_Rule/refs/heads/master/Clash/ZJU-More-Scholar.list
ruleset=💬 Ai平台,https://raw.githubusercontent.com/ZY-Zeng/ZJU_Rule/refs/heads/master/Clash/Ruleset/AI.list
ruleset=💬 Ai平台,https://raw.githubusercontent.com/ZY-Zeng/ZJU_Rule/refs/heads/master/Clash/Ruleset/OpenAi.list
ruleset=🎯 全球直连,https://raw.githubusercontent.com/ZY-Zeng/ZJU_Rule/refs/heads/master/Clash/LocalAreaNetwork.list
ruleset=🎯 全球直连,https://raw.githubusercontent.com/ZY-Zeng/ZJU_Rule/refs/heads/master/Clash/UnBan.list
ruleset=🛑 广告拦截,https://raw.githubusercontent.com/ZY-Zeng/ZJU_Rule/refs/heads/master/Clash/BanAD.list
ruleset=🍃 应用净化,https://raw.githubusercontent.com/ZY-Zeng/ZJU_Rule/refs/heads/master/Clash/BanProgramAD.list
ruleset=🆎 AdBlock,https://raw.githubusercontent.com/ZY-Zeng/ZJU_Rule/refs/heads/master/Clash/BanEasyList.list
ruleset=🆎 AdBlock,https://raw.githubusercontent.com/ZY-Zeng/ZJU_Rule/refs/heads/master/Clash/BanEasyListChina.list
ruleset=🛡️ 隐私防护,https://raw.githubusercontent.com/ZY-Zeng/ZJU_Rule/refs/heads/master/Clash/BanEasyPrivacy.list
ruleset=📢 谷歌FCM,https://raw.githubusercontent.com/ZY-Zeng/ZJU_Rule/refs/heads/master/Clash/Ruleset/GoogleFCM.list
ruleset=🎯 全球直连,https://raw.githubusercontent.com/ZY-Zeng/ZJU_Rule/refs/heads/master/Clash/GoogleCN.list
ruleset=🎯 全球直连,https://raw.githubusercontent.com/ZY-Zeng/ZJU_Rule/refs/heads/master/Clash/Ruleset/SteamCN.list
ruleset=🎯 全球直连,https://raw.githubusercontent.com/ZY-Zeng/ZJU_Rule/refs/heads/master/Clash/Ruleset/Adobe.list
ruleset=Ⓜ️ 微软Bing,https://raw.githubusercontent.com/ZY-Zeng/ZJU_Rule/refs/heads/master/Clash/Bing.list
ruleset=Ⓜ️ 微软云盘,https://raw.githubusercontent.com/ZY-Zeng/ZJU_Rule/refs/heads/master/Clash/OneDrive.list
ruleset=Ⓜ️ 微软服务,https://raw.githubusercontent.com/ZY-Zeng/ZJU_Rule/refs/heads/master/Clash/Microsoft.list
ruleset=🍎 苹果服务,https://raw.githubusercontent.com/ZY-Zeng/ZJU_Rule/refs/heads/master/Clash/Apple.list
ruleset=📲 电报消息,https://raw.githubusercontent.com/ZY-Zeng/ZJU_Rule/refs/heads/master/Clash/Telegram.list
ruleset=🎶 网易音乐,https://raw.githubusercontent.com/ZY-Zeng/ZJU_Rule/refs/heads/master/Clash/Ruleset/NetEaseMusic.list
ruleset=🎮 游戏平台,https://raw.githubusercontent.com/ZY-Zeng/ZJU_Rule/refs/heads/master/Clash/Ruleset/Epic.list
ruleset=🎮 游戏平台,https://raw.githubusercontent.com/ZY-Zeng/ZJU_Rule/refs/heads/master/Clash/Ruleset/Origin.list
ruleset=🎮 游戏平台,https://raw.githubusercontent.com/ZY-Zeng/ZJU_Rule/refs/heads/master/Clash/Ruleset/Sony.list
ruleset=🎮 游戏平台,https://raw.githubusercontent.com/ZY-Zeng/ZJU_Rule/refs/heads/master/Clash/Ruleset/Steam.list
ruleset=🎮 游戏平台,https://raw.githubusercontent.com/ZY-Zeng/ZJU_Rule/refs/heads/master/Clash/Ruleset/Nintendo.list
ruleset=📹 油管视频,https://raw.githubusercontent.com/ZY-Zeng/ZJU_Rule/refs/heads/master/Clash/Ruleset/YouTube.list
ruleset=🎥 奈飞视频,https://raw.githubusercontent.com/ZY-Zeng/ZJU_Rule/refs/heads/master/Clash/Ruleset/Netflix.list
ruleset=📺 巴哈姆特,https://raw.githubusercontent.com/ZY-Zeng/ZJU_Rule/refs/heads/master/Clash/Ruleset/Bahamut.list
ruleset=📺 哔哩哔哩,https://raw.githubusercontent.com/ZY-Zeng/ZJU_Rule/refs/heads/master/Clash/Ruleset/BilibiliHMT.list
ruleset=📺 哔哩哔哩,https://raw.githubusercontent.com/ZY-Zeng/ZJU_Rule/refs/heads/master/Clash/Ruleset/Bilibili.list
ruleset=🌏 国内媒体,https://raw.githubusercontent.com/ZY-Zeng/ZJU_Rule/refs/heads/master/Clash/ChinaMedia.list
ruleset=🌍 国外媒体,https://raw.githubusercontent.com/ZY-Zeng/ZJU_Rule/refs/heads/master/Clash/ProxyMedia.list
ruleset=🚀 节点选择,https://raw.githubusercontent.com/ZY-Zeng/ZJU_Rule/refs/heads/master/Clash/ProxyGFWlist.list
;ruleset=🎯 全球直连,https://raw.githubusercontent.com/ZY-Zeng/ZJU_Rule/refs/heads/master/Clash/ChinaIp.list
ruleset=🎯 全球直连,https://raw.githubusercontent.com/ZY-Zeng/ZJU_Rule/refs/heads/master/Clash/ChinaDomain.list
ruleset=🎯 全球直连,https://raw.githubusercontent.com/ZY-Zeng/ZJU_Rule/refs/heads/master/Clash/ChinaCompanyIp.list
ruleset=🎯 全球直连,https://raw.githubusercontent.com/ZY-Zeng/ZJU_Rule/refs/heads/master/Clash/Download.list
ruleset=✔ ZJU内网,https://raw.githubusercontent.com/ZY-Zeng/ZJU_Rule/refs/heads/master/Clash/ZJU-IP.list
;ruleset=🎯 全球直连,[]GEOIP,LAN
ruleset=🎯 全球直连,[]GEOIP,CN
ruleset=🐟 漏网之鱼,[]FINAL
;设置规则标志位

;设置分组标志位
custom_proxy_group=✉️ 通知公告`select`(✉️)
custom_proxy_group=🚀 节点选择`select`[]♻️ 自动选择`[]🔯 故障转移`[]🔮 负载均衡`[]🇭🇰 香港节点`[]🇨🇳 台湾节点`[]🇸🇬 狮城节点`[]🇯🇵 日本节点`[]🇺🇲 美国节点`[]🇰🇷 韩国节点`[]🚀 手动切换`[]DIRECT
custom_proxy_group=🚀 手动切换`select`(^(?!.*✉️).*)
custom_proxy_group=♻️ 自动选择`url-test`(^(?!.*(ZJU|浙大|内网|✉️)).*)`http://www.gstatic.com/generate_204`300,,50
custom_proxy_group=🔯 故障转移`fallback`(^(?!.*(ZJU|浙大|内网|✉️)).*)`http://www.gstatic.com/generate_204`300,,50
custom_proxy_group=🔮 负载均衡`load-balance`(^(?!.*(ZJU|浙大|内网|✉️)).*)`http://www.gstatic.com/generate_204`300,,50
custom_proxy_group=✔ ZJU内网`select`[]DIRECT`(ZJU|浙大|内网)`[]🚀 节点选择
custom_proxy_group=📃 ZJU More Scholar`select`[]🚀 节点选择`(ZJU|浙大|内网)`[]DIRECT
custom_proxy_group=💬 Ai平台`select`[]🚀 节点选择`[]♻️ 自动选择`[]🇸🇬 狮城节点`[]🇭🇰 香港节点`[]🇨🇳 台湾节点`[]🇯🇵 日本节点`[]🇺🇲 美国节点`[]🇰🇷 韩国节点`[]🚀 手动切换`(^(?!.*✉️).*)`[]DIRECT
custom_proxy_group=📲 电报消息`select`[]🚀 节点选择`[]♻️ 自动选择`[]🇸🇬 狮城节点`[]🇭🇰 香港节点`[]🇨🇳 台湾节点`[]🇯🇵 日本节点`[]🇺🇲 美国节点`[]🇰🇷 韩国节点`[]🚀 手动切换`[]DIRECT
custom_proxy_group=📹 油管视频`select`[]🚀 节点选择`[]♻️ 自动选择`[]🇸🇬 狮城节点`[]🇭🇰 香港节点`[]🇨🇳 台湾节点`[]🇯🇵 日本节点`[]🇺🇲 美国节点`[]🇰🇷 韩国节点`[]🚀 手动切换`[]DIRECT
custom_proxy_group=🎥 奈飞视频`select`[]🎥 奈飞节点`[]🚀 节点选择`[]♻️ 自动选择`[]🇸🇬 狮城节点`[]🇭🇰 香港节点`[]🇨🇳 台湾节点`[]🇯🇵 日本节点`[]🇺🇲 美国节点`[]🇰🇷 韩国节点`[]🚀 手动切换`[]DIRECT
custom_proxy_group=📺 巴哈姆特`select`[]🇨🇳 台湾节点`[]🚀 节点选择`[]🚀 手动切换`[]DIRECT
custom_proxy_group=📺 哔哩哔哩`select`[]🎯 全球直连`[]🇨🇳 台湾节点`[]🇭🇰 香港节点`[]🚀 手动切换
custom_proxy_group=🌍 国外媒体`select`[]🚀 节点选择`[]♻️ 自动选择`[]🇭🇰 香港节点`[]🇨🇳 台湾节点`[]🇸🇬 狮城节点`[]🇯🇵 日本节点`[]🇺🇲 美国节点`[]🇰🇷 韩国节点`[]🚀 手动切换`[]DIRECT
custom_proxy_group=🌏 国内媒体`select`[]DIRECT`[]🇭🇰 香港节点`[]🇨🇳 台湾节点`[]🇸🇬 狮城节点`[]🇯🇵 日本节点`[]🚀 手动切换
custom_proxy_group=📢 谷歌FCM`select`[]DIRECT`[]🚀 节点选择`[]🇺🇲 美国节点`[]🇭🇰 香港节点`[]🇨🇳 台湾节点`[]🇸🇬 狮城节点`[]🇯🇵 日本节点`[]🇰🇷 韩国节点`[]🚀 手动切换
custom_proxy_group=Ⓜ️ 微软Bing`select`[]DIRECT`[]🚀 节点选择`[]🇺🇲 美国节点`[]🇭🇰 香港节点`[]🇨🇳 台湾节点`[]🇸🇬 狮城节点`[]🇯🇵 日本节点`[]🇰🇷 韩国节点`[]🚀 手动切换
custom_proxy_group=Ⓜ️ 微软云盘`select`[]DIRECT`[]🚀 节点选择`[]🇺🇲 美国节点`[]🇭🇰 香港节点`[]🇨🇳 台湾节点`[]🇸🇬 狮城节点`[]🇯🇵 日本节点`[]🇰🇷 韩国节点`[]🚀 手动切换
custom_proxy_group=Ⓜ️ 微软服务`select`[]DIRECT`[]🚀 节点选择`[]🇺🇲 美国节点`[]🇭🇰 香港节点`[]🇨🇳 台湾节点`[]🇸🇬 狮城节点`[]🇯🇵 日本节点`[]🇰🇷 韩国节点`[]🚀 手动切换
custom_proxy_group=🍎 苹果服务`select`[]DIRECT`[]🚀 节点选择`[]🇺🇲 美国节点`[]🇭🇰 香港节点`[]🇨🇳 台湾节点`[]🇸🇬 狮城节点`[]🇯🇵 日本节点`[]🇰🇷 韩国节点`[]🚀 手动切换
custom_proxy_group=🎮 游戏平台`select`[]DIRECT`[]🚀 节点选择`[]🇺🇲 美国节点`[]🇭🇰 香港节点`[]🇨🇳 台湾节点`[]🇸🇬 狮城节点`[]🇯🇵 日本节点`[]🇰🇷 韩国节点`[]🚀 手动切换
custom_proxy_group=🎶 网易音乐`select`[]DIRECT`[]🚀 节点选择`[]♻️ 自动选择`(网易|音乐|解锁|Music|NetEase)
custom_proxy_group=🎯 全球直连`select`[]DIRECT`[]🚀 节点选择`[]♻️ 自动选择
custom_proxy_group=🛑 广告拦截`select`[]REJECT`[]DIRECT
custom_proxy_group=🍃 应用净化`select`[]REJECT`[]DIRECT
custom_proxy_group=🆎 AdBlock`select`[]REJECT`[]DIRECT
custom_proxy_group=🛡️ 隐私防护`select`[]REJECT`[]DIRECT
custom_proxy_group=🐟 漏网之鱼`select`[]🚀 节点选择`[]♻️ 自动选择`[]DIRECT`[]🇭🇰 香港节点`[]🇨🇳 台湾节点`[]🇸🇬 狮城节点`[]🇯🇵 日本节点`[]🇺🇲 美国节点`[]🇰🇷 韩国节点`[]🚀 手动切换
custom_proxy_group=🇭🇰 香港节点`url-test`(港|HK|Hong Kong)`http://www.gstatic.com/generate_204`300,,50
custom_proxy_group=🇯🇵 日本节点`url-test`(日本|川日|东京|大阪|泉日|埼玉|沪日|深日|[^-]日|JP|Japan|Tokyo)`http://www.gstatic.com/generate_204`300,,50
custom_proxy_group=🇺🇲 美国节点`url-test`(美|波特兰|达拉斯|俄勒冈|凤凰城|费利蒙|硅谷|拉斯维加斯|洛杉矶|圣何塞|圣克拉拉|西雅图|芝加哥|US|United States|Los Angeles|San Jose)`http://www.gstatic.com/generate_204`300,,150
custom_proxy_group=🇨🇳 台湾节点`url-test`(台|新北|彰化|TW|Taiwan|Taipei)`http://www.gstatic.com/generate_204`300,,50
custom_proxy_group=🇸🇬 狮城节点`url-test`(新加坡|坡|狮城|SG|Singapore)`http://www.gstatic.com/generate_204`300,,50
custom_proxy_group=🇰🇷 韩国节点`url-test`(KR|kr|Korea|KOR|首尔|韩|韓)`http://www.gstatic.com/generate_204`300,,50
custom_proxy_group=🎥 奈飞节点`select`(NF|奈飞|解锁|Netflix|NETFLIX|Media|netflix|nf|nfo|allmedia)
;设置分组标志位

enable_rule_generator=true
overwrite_original_rules=true

;clash_rule_base=https://raw.githubusercontent.com/ZY-Zeng/ZJU_Rule/refs/heads/master/Clash/GeneralClashConfig.yml

;luck
